---
- name: Run .osx dotfiles.
  ansible.builtin.command: "{{ osx_script }}"
  changed_when: false

- name: Clone python autoswitch
  ansible.builtin.git:
    repo: https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv.git
    dest: ~/.oh-my-zsh/custom/plugins/autoswitch_virtualenv
    version: master
